"""
Catálogo: las áreas, es decir, los montajes para crear. Cada una junta qué preset de cada equipo,
qué bancos de Analog Lab y qué pistas del DAW se usan para un tipo de trabajo.

Las decisiones musicales (tempo, tonalidad, acordes, motivo) no van aquí: son tuyas.
KeyStep y Casio quedan como «pendiente» hasta que tengan sus presets en 8. Setup/4. Presets/.
"""

ANTES = [
    'Cierra MidiSuite y MIDI Control Center: ocupan el puerto MIDI de sus aparatos.',
    'SMC-PAD: Glob → **Transpose = 0**.',
    'Analog Lab, Settings → MIDI: *MIDI Controller* = **Generic 9 Knobs + 9 Faders**, *MIDI Channel* = **All**, *MIDI Config* = **Beat Maker**.',
    'En el DAW: pistas de instrumento con Analog Lab, y *Input Echo* encendido solo en la pista que vas a tocar.',
]

AREAS = [
    dict(n=1, nombre='Beats',
         para='Armar un **beat por capas** (batería, bajo, acordes o arpegio, efectos) y grabarlo.',
         equipo=[('SMC-PAD', 'P3 Beat Maker (batería), P2 Bajo, P4 Teclas (acordes, arpegiadores y FX)'),
                 ('KeyStep', 'pendiente'), ('Casio', 'no hace falta')],
         presets_smcpad=[3, 2, 4],
         bancos=['Beat Maker', 'Bajo', 'Teclas', 'Pads', 'Arpegiadores', 'FX'],
         pistas=[('Batería', 'SMC-PAD · canal 10', 'un kit de *Beat Maker*', 'P3'),
                 ('Bajo', 'SMC-PAD · canal 1', 'un preset de *Bajo*', 'P2'),
                 ('Acordes', 'SMC-PAD · canal 1', '*Teclas* o *Pads*', 'P4'),
                 ('Arpegio', 'SMC-PAD · canal 1', '*Arpegiadores*', 'P4 (mantén el pad, o Hold)'),
                 ('FX', 'SMC-PAD · canal 1', '*FX*', 'P4')],
         pasos=['Fija el tempo del proyecto y enciende el metrónomo.',
                '**Batería:** P3, banco 1 de pads. Graba un patrón corto en bucle. Con las perillas B (KNOB BANK) equilibras el kit.',
                '**Bajo:** cambia el pad a P2, selecciona la pista *Bajo* y graba.',
                '**Acordes o arpegio:** P4, en su pista. Los *Arpegiadores* siguen el tempo del proyecto.',
                '**FX:** las subidas (*And Away*, *Bassement Riser*) justo antes de un cambio de sección.',
                'Exporta el audio y anótalo en la bitácora.'],
         listo='Un audio exportado del beat, aunque sea un bucle corto. Cuenta como el audio de la semana (bucle ⑤ de [[6. Práctica/0. Flujos|Flujos]]).'),
    dict(n=2, nombre='Canción',
         para='Trabajar la **obra activa**: probar acordes, melodía y arreglo con sonidos que encajan con dream pop y folk.',
         equipo=[('Casio', 'piano (pendiente)'), ('KeyStep', 'acordes y melodía (pendiente)'),
                 ('SMC-PAD', 'P4 Teclas (acordes en cuartas, como en la guitarra), P3 Beat Maker (batería sencilla), P2 Bajo')],
         presets_smcpad=[4, 3, 2],
         bancos=['Teclas', 'Pads', 'Leads', 'Texturas', 'Beat Maker', 'Bajo'],
         pistas=[('Piano', 'Casio · USB MIDI', '*Teclas* (o el sonido del propio Casio)', '—'),
                 ('Acordes', 'KeyStep o SMC-PAD · canal 1', '*Teclas* o *Pads*', 'P4'),
                 ('Melodía', 'KeyStep', '*Leads*', '—'),
                 ('Fondo', 'SMC-PAD · canal 1', '*Texturas*', 'P4'),
                 ('Batería', 'SMC-PAD · canal 10', '*Beat Maker In The Air* o *606*', 'P3'),
                 ('Bajo', 'SMC-PAD · canal 1', '*Fret Bass* o *Fretless Bass*', 'P2')],
         pasos=['Abre la nota de la obra activa y escribe qué vas a probar hoy.',
                'Monta solo las pistas que necesites para eso.',
                'Graba cada idea como una toma corta, sin pulirla.',
                'Registra en la nota de la obra qué decidiste y por qué (bucle ②).'],
         listo='Lo que pide el bucle ② de [[6. Práctica/0. Flujos|Flujos]] para la obra: decisión registrada y su audio.'),
    dict(n=3, nombre='Atmósferas',
         para='Hacer **fondos, intros e interludios**: texturas que evolucionan, arpegios sostenidos y efectos.',
         equipo=[('SMC-PAD', 'P4 Teclas, con *Latch* en Glob o *Hold* en Analog Lab'), ('KeyStep', 'sostener notas (pendiente)'),
                 ('Casio', 'no hace falta')],
         presets_smcpad=[4],
         bancos=['Texturas', 'Pads', 'Arpegiadores', 'FX'],
         pistas=[('Textura', 'SMC-PAD · canal 1', '*Texturas*', 'P4'),
                 ('Pad', 'SMC-PAD · canal 1', '*Pads*', 'P4'),
                 ('Arpegiador', 'SMC-PAD · canal 1', '*Arpegiadores* (con Hold)', 'P4'),
                 ('FX', 'SMC-PAD · canal 1', '*FX*', 'P4')],
         pasos=['Elige una textura y sostenla: *Latch* en el SMC-PAD o *Hold* en Analog Lab.',
                'Ajusta *Reverb* y *Delay* con las perillas A (7 y 6) hasta que el fondo respire.',
                'Suma un arpegiador en otra pista.',
                'Usa un *FX* para entrar o salir.',
                'Graba una toma larga sin cortar y recorta después.'],
         listo='Una toma de audio que sirva como intro, puente o final de una pieza.'),
    dict(n=4, nombre='Jam con Strudel',
         para='Tocar **sobre la banda de Strudel** (bajo, pad y arpegio) con el SMC-PAD y el KeyStep.',
         equipo=[('SMC-PAD', 'P8 Strudel'), ('KeyStep', '`HUM - Lead` (pendiente)'), ('Casio', 'no hace falta')],
         presets_smcpad=[8],
         bancos=['Bajo', 'Pads', 'Texturas', 'Arpegios', 'Beat Maker', 'Leads'],
         pistas=[('STR - Bass', 'Strudel y SMC-PAD · canal 2', '*Bajo*', 'P8 bancos 1–2'),
                 ('STR - Pad', 'Strudel y SMC-PAD · canal 3', '*Pads* o *Texturas*', 'P8 bancos 3–4'),
                 ('STR - Arp', 'Strudel y SMC-PAD · canal 4', '*Arpegios* (no *Arpegiadores*)', 'P8 bancos 5–6'),
                 ('Batería', 'SMC-PAD · canal 10', '*Beat Maker*', 'P8 bancos 7–8'),
                 ('HUM - Lead', 'KeyStep', '*Leads*', '—')],
         pasos=['Arranca Strudel como dice [[4. Instrumento/2. Strudel/2. House y todo|House y todo]].',
                'Pon la entrada de cada pista `STR` en *Omni* (o SMC-PAD) con su canal, e *Input Echo* encendido.',
                'P8: perillas A = volumen y brillo de cada voz; perillas B = reverb y delay.',
                'Toca encima y graba la toma.'],
         listo='Una toma grabada de la jam.'),
]
